kind: Service
apiVersion: v1
metadata:
  name: confluence
  labels:
    app: confluence
spec:
  selector:
    app: confluence
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8090
  - name: synchrony
    protocol: TCP
    port: 8091
    targetPort: 8091
  type: LoadBalancer
